spring:
  profiles:
    active: dev
    servlet:
      multipart:
        max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

server:
  servlet:
    context-path: /api/v1/